version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es01
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  db: 
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_chat_system:/var/lib/mysql:delegated
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server
  rabbitmq:
    image: rabbitmq:3.6.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build: .
    command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - ES_HOST=es01
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
    depends_on:
      - db
      - redis
      - rabbitmq
    links:
      - db
      - redis
      - es01
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp
      - gems_cache:/gems
  sidekiq:
    build: .
    restart: on-failure
    volumes:
      - .:/myapp
    command: bundle exec sidekiq 
    depends_on:
      - db
      - redis
      - web
    environment:
      - REDIS_HOST=redis
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - ES_HOST=es01
  rufus_worker:
    build: .
    volumes:
      - .:/myapp
    restart: on-failure
    command: bundle exec rake rufus_job 
    depends_on:
      - web
      - db
  sneakers:
    build: .
    command: './wait-for-it.sh -t 20 rabbitmq:5672 -- bundle exec rake sneakers:run'
    depends_on:
      - web
      - rabbitmq
    volumes:
      - .:/app
      - gems_cache:/gems
    environment:
      RAILS_ENV: development
      WORKERS: ApplicationsWorker
volumes:
  redis:
  data01:
  myapp:
  mysql_chat_system:
  gems_cache:
# networks:
#   host:
#     name: 'chat-system-default'